language: rust

os:
  - linux

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get install -y -qq screenfetch
  - screenfetch
  - sudo apt-get install -y -qq libxxf86vm1 libxxf86vm-dev