[package]
name = "ionic_engine"
version = "1.0.0-1"
authors = ["w67clement"]

[dependencies]
gl = "0.6.*"

[dependencies.glfw]
git = "https://github.com/PistonDevelopers/glfw-rs.git"
#default-features = false

